apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "RHODS Project (GUID: {{ guid }})"
    openshift.io/requester: "retail"
  name: "retail-rhods-project"
