apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-workaround993-rolebinding
  namespace: retail-rhods-project
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
roleRef:
  kind: Role 
  name: argocd-workaround993-role
  apiGroup: rbac.authorization.k8s.io
